* ChangeLog

** 0.2.1

Updating Piggieback to 0.1.5, thanks again [[https://github.com/mfikes][Mike Fikes]]!

** 0.2.0

Simple-bREPL has been updated to take account of the breaking changes
in CLJS 0.0-2665.

Weasel and Piggieback dependencies updated.

No other changes to Simple-bREPL.

Thanks to [[https://github.com/mfikes][Mike Fikes]] and [[https://github.com/viesti][Kimmo Koskinen]] for reminding me when the
upstream libraries were updated!

** 0.1.2

No breaking changes.

Minor change to the CLJS-side to make a variable access safer - thanks
to [[https://github.com/joelash][Joel Friedman]] for the PR :)

Upgraded to Weasel 0.4.2 to fix a couple of upstream bugs.

** 0.1.1 

No breaking changes.

Deprecation: ={:brepl-port 9002}= in your project.clj should replaced
by ={:brepl {:port 9002}}= - original will be removed in 0.2.0.

You can now choose the IP address to bind on, by providing (for
example) ={:brepl {:ip "0.0.0.0", :port 9002}}= in your project.clj.

Thanks to [[https://github.com/mfikes][Mike Fikes]] for his suggestion and subsequent PR.

** 0.1.0

Initial release.
